version: '3.8'

services:
  mariadb:
    image: mariadb:10.9
    container_name: glpi-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: glpi_root_password
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi_password
    volumes:
      - glpi_mariadb_data:/var/lib/mysql
    networks:
      - glpi-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  glpi:
    image: diouxx/glpi:latest
    container_name: glpi-app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      TIMEZONE: America/Mexico_City
      GLPI_LANG: es_MX
    volumes:
      - glpi_files:/var/www/html/files
      - glpi_config:/var/www/html/config
      - glpi_marketplace:/var/www/html/marketplace
      - glpi_plugins:/var/www/html/plugins
    networks:
      - glpi-network
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  glpi_mariadb_data:
    driver: local
  glpi_files:
    driver: local
  glpi_config:
    driver: local
  glpi_marketplace:
    driver: local
  glpi_plugins:
    driver: local

networks:
  glpi-network:
    driver: bridge