apiVersion: apps/v1
kind: Deployment
metadata:
  name: axity-lab-app
  namespace: axity
  labels:
    app: axity-lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axity-lab-app
  template:
    metadata:
      labels:
        app: axity-lab-app
    spec:
      containers:
      - name: app
        image: axity-lab-app:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
