apiVersion: v1
kind: Service
metadata:
  name: axity-lab-app-service
  namespace: axity
  labels:
    app: axity-lab-app
spec:
  type: ClusterIP
  selector:
    app: axity-lab-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
