---
- name: Patch Operating System (Update packages)
  hosts: all
  become: yes
  
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages to latest version
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"
      register: upgrade_result

    - name: Update yum packages (RedHat/CentOS)
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
      register: yum_upgrade_result

    - name: Check if reboot is required (Debian/Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family == "Debian"

    - name: Display upgrade summary (Debian/Ubuntu)
      debug:
        msg: 
          - "Packages upgraded: {{ upgrade_result.changed }}"
          - "Reboot required: {{ reboot_required_file.stat.exists | default(false) }}"
      when: ansible_os_family == "Debian"

    - name: Display upgrade summary (RedHat/CentOS)
      debug:
        msg: "Packages upgraded: {{ yum_upgrade_result.changed }}"
      when: ansible_os_family == "RedHat"

    - name: Notify about reboot requirement
      debug:
        msg: "ATTENTION: System reboot is required to complete updates!"
      when: 
        - ansible_os_family == "Debian"
        - reboot_required_file.stat.exists